name: Streamlit Keep Alive

on:
  schedule:
    # UTC（世界標準時）で設定。2時間ごとに実行
    - cron: '0 */2 * * *'
  workflow_dispatch: # Actionsタブから手動でも実行できるようにする

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Access Streamlit App
        # GETリクエストでコンテンツを取得してアプリを起動
        run: |
          curl -L https://kuga-99para.streamlit.app
          curl -L https://kuga-99para-ch.streamlit.app
          echo "Apps pinged at $(date)"
